[build]
  base = "web"
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_STRAPI_URL = "https://truthful-gift-3408f45803.strapiapp.com"
  NEXT_PUBLIC_SITE_URL = "https://your-netlify-site.netlify.app"