name: Deploy Web Frontend to Vercel

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install dependencies
        working-directory: ./web
        run: npm ci

      - name: Run linting
        working-directory: ./web
        run: npm run lint

      - name: Build application
        working-directory: ./web
        run: npm run build
        env:
          NEXT_PUBLIC_STRAPI_URL: ${{ secrets.NEXT_PUBLIC_STRAPI_URL }}
          STRAPI_API_TOKEN: ${{ secrets.STRAPI_API_TOKEN }}
          REVALIDATE_SECRET: ${{ secrets.REVALIDATE_SECRET }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          RESEND_FROM_EMAIL: ${{ secrets.RESEND_FROM_EMAIL }}

      - name: Deploy to Vercel
        if: ${{ secrets.VERCEL_TOKEN != '' && secrets.VERCEL_ORG_ID != '' && secrets.VERCEL_PROJECT_ID != '' }}
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./web
          vercel-args: '--prod'

      - name: Vercel Deployment Skipped
        if: ${{ secrets.VERCEL_TOKEN == '' || secrets.VERCEL_ORG_ID == '' || secrets.VERCEL_PROJECT_ID == '' }}
        run: |
          echo "⚠️ Vercel deployment skipped - missing required secrets:"
          echo "   VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN != '' && '✅ Set' || '❌ Missing' }}"
          echo "   VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID != '' && '✅ Set' || '❌ Missing' }}"
          echo "   VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID != '' && '✅ Set' || '❌ Missing' }}"
          echo ""
          echo "📖 To enable Vercel deployment:"
          echo "   1. Go to your repository Settings → Secrets and variables → Actions"
          echo "   2. Add the required Vercel secrets"
          echo "   3. See DEPLOYMENT.md for detailed setup instructions"
