name: Test Workflow

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test workflow
        run: |
          echo "GitHub Actions is working!"
          echo "Current branch: ${{ github.ref_name }}"
          echo "Repository: ${{ github.repository }}"
