[build]
  publish = "out"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Handle client-side routing for Next.js static export
# Specific routes first
[[redirects]]
  from = "/auth/reset-password"
  to = "/reset-password/"
  status = 200

[[redirects]]
  from = "/auth/forgot-password"
  to = "/forgot-password/"
  status = 200

[[redirects]]
  from = "/auth/signin"
  to = "/signin/"
  status = 200

[[redirects]]
  from = "/auth/login"
  to = "/signin/"
  status = 200

[[redirects]]
  from = "/auth/signup"
  to = "/signup/"
  status = 200

# Catch-all for other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"